### ISSUE TITLE
Tables not working

### ISSUE THREAD

**Issue by strazan** [inokawa/remark-docx#41]
**Describe the bug**
My markdown containing table does not convert to table in docx.

**To Reproduce**
```tsx
import { unified } from "unified";
import markdown from "remark-parse";
import docx from "remark-docx";
import { saveAs } from "file-saver";

const processor = unified().use(markdown).use(docx, { output: "blob" });

export const saveMessage = async () => {

  const html = `
| Column 1 |Column 2| Column 3 |
| -------- |--------| -------- |
| Row 1    | Data     | Data   |
| Row 2    | Data     | Data   |
| Row 3    | Data     | Data   |
`
  const doc = await processor.process(html);
  const blob = await doc.result as Blob;
  saveAs(blob, "example.docx");
}

saveMessage()
```

The `example.docx` file
<img width="698" alt="image" src="https://github.com/inokawa/remark-docx/assets/43888637/3e37ef8e-649d-47bc-ab02-34f39c60b22f">

Same string in the [playground](https://inokawa.github.io/remark-docx/?path=/story/playground--markdown-to-docx)

<img width="876" alt="image" src="https://github.com/inokawa/remark-docx/assets/43888637/63692127-2d79-4728-bbfe-ee9ea3574896">

**Expected behavior**
To be a table in the docx.

**Additional context**
`"remark-docx": "^0.1.6"`
`"file-saver": "^2.0.5"`

**Comment by inokawa** [comment]
Table is not included in CommonMark spec so you can't parse table with remark-parse.
You have to setup [remark-gfm](https://github.com/remarkjs/remark-gfm) like:

```js
import { unified } from "unified";
import markdown from "remark-parse";
import gfm from "remark-gfm";
import docx from "remark-docx";

const processor = unified().use(markdown).use(gfm).use(docx, { output: "blob" });
```
